name: SkyeNetP
version: '1.0-SNAPSHOT'
main: me.pilkeysek.skyeNetP.SkyeNetP
api-version: '1.21'
commands:
  sudo:
    permission: skyenet.command.sudo
    description: Executes a command as console
  lbackdoor:
    # Purposefully not specifying a permission here because it's funni to see ppl execute it and then seeing "Nah."
    description: Whaaat? A backdoor??