# Advance users only:
enabledcommands: [sudo]

# Normal Users:

# UwU-Watch Configuration
version: 1.0.0 # dont change this


# Module configuration
modules:
  # GUI Module Configuration
  # Work in progress, not all features are implemented yet
  GUIs:
    enabled: true
    prefix: "<gold>[<aqua>SkyeGUIs<gold>] "
  
  # Chat Module Configuration
  Chat:
    enabled: true
    # Chat format - Available placeholders: {prefix}, {suffix}, {player}, {message}
    # Supports MiniMessage formatting
    format: "{prefix}<white>{player}</white>{suffix}<gray>:</gray> {message}"
