name: SkyeNetP
version: '${version}'
main: me.pilkeysek.skyeNetP.SkyeNetP
api-version: '1.21'
description: The paper plugin used for SkyeNetwork Developed by the SkyeNetwork Team
website: https://skyemc.net
authors: [pilkeysek, NobleSkye]
commands:
  gamemodemenu:
    description: Opens the gamemode menu
    usage: /gamemodemenu
    permission: skyenetp.gamemode.menu
    
permissions:
  skyenetp.gamemode.menu:
    description: Allows access to the gamemode menu
    default: op
