name: SkyeNetP
version: '${version}'
main: me.pilkeysek.skyeNetP.SkyeNetP
api-version: '1.21'
description: The paper plugin used for SkyeNetwork Developed by the SkyeNetwork Team
website: https://skyemc.net
authors: [SkyeNetwork Team]
modrinth-project-id: "IBSpJfbm"
commands:
  creative:
    description: Opens the gamemode menu
    usage: /creative
    permission: skyenetp.command.creativemenu
  skyenetp:
    description: SkyeNetP plugin management
    usage: /skyenetp reload
    permission: skyenetp.command.reload
    
permissions:
  skyenetp.command.creativemenu:
    description: Changes gamemode to creative & adventure for who has ranks
    default: op
  skyenetp.command.reload:
    description: Allows reloading of the SkyeNetP plugin
    default: op
