name: Build Plugin

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    
    - name: Build with Gradle
      run: ./gradlew build
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Plugin JAR
        path: build/libs/*.jar
        if-no-files-found: error

    - name: Check commit message
      id: check_commit
      run: |
        commit_msg=$(git log -1 --pretty=%B)
        if [[ $commit_msg == release:* ]]; then
          echo "is_release=true" >> $GITHUB_OUTPUT
          version=$(echo $commit_msg | sed 's/release: //')
        else
          echo "is_release=false" >> $GITHUB_OUTPUT
          version="beta-$(git rev-parse --short HEAD)"
        fi
        echo "version=$version" >> $GITHUB_OUTPUT

    - name: Create Release
      if: steps.check_commit.outputs.is_release == 'true'
      uses: softprops/action-gh-release@v1
      with:
        files: build/libs/*.jar
        tag_name: v${{ steps.check_commit.outputs.version }}
        name: Release ${{ steps.check_commit.outputs.version }}
        draft: false
        prerelease: false
        generate_release_notes: true
        make_latest: true
        target_commitish: ${{ github.sha }}

    - name: Create Beta Release
      if: steps.check_commit.outputs.is_release != 'true'
      uses: softprops/action-gh-release@v1
      with:
        files: build/libs/*.jar
        tag_name: beta-${{ github.sha }}
        name: Beta Build ${{ steps.check_commit.outputs.version }}
        draft: false
        prerelease: true
        generate_release_notes: true
        make_latest: false
